/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDL_H_RPCGEN
#define _IDL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct values {
	float num1;
	float num2;
	char operation;
};
typedef struct values values;

#define COMPUTE 12345567
#define COMPUTE_VERS 5

#if defined(__STDC__) || defined(__cplusplus)
#define CAL 1
extern  float * cal_5(values *, CLIENT *);
extern  float * cal_5_svc(values *, struct svc_req *);
extern int compute_5_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CAL 1
extern  float * cal_5();
extern  float * cal_5_svc();
extern int compute_5_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_values (XDR *, values*);

#else /* K&R C */
extern bool_t xdr_values ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IDL_H_RPCGEN */
