/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IDL.h"

float *
cal_5_svc(values *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	switch(argp->operation){
		case '+':result=argp->num1+argp->num2;
			 break;
		case '-':result=argp->num1-argp->num2;
			 break;
		case '*':result=argp->num1*argp->num2;
			 break;
		case '/':result=argp->num1/argp->num2;
			 break;
//		case '%':result=argp->num1%argp->num2;
//			 break;
	}

	return &result;
}
