/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IDL.h"


float 
compute_5(char *host,float num1,float num2,char op)
{
	CLIENT *clnt;
	float  *result_1;
	values  cal_5_arg;
	cal_5_arg.num1=num1;
	cal_5_arg.num2=num2;
	cal_5_arg.operation=op;
#ifndef	DEBUG
	clnt = clnt_create (host, COMPUTE, COMPUTE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = cal_5(&cal_5_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return (*result_1);
}


int
main (int argc, char *argv[])
{
	char *host;
	float num1;
	float num2;
	char oper;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	printf("Enter two numbers followed by operation\n");
	scanf("%f",&num1);
	scanf("%f",&num2);
	scanf("%s",&oper);


	printf("Result:%f\n",compute_5 (host,num1,num2,oper));
exit (0);
}
